name: 有 趣 的 名 字

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: list all
      run: ls -la
    - name: pwd
      run: pwd
